server:
  port: 8766
netty:
  port: 10801
rocketmq:
  name-server: mq.hocgin.dev:9876
  producer:
    group: BOSSER_PRODUCER_GROUP
logging:
  level:
    in.hocg: debug
    io.netty: debug
    org.apache.rocketmq: debug